name: CI
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/flathub-infra/flatpak-github-actions:kde-6.8
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flathub-infra/flatpak-github-actions/flatpak-builder@master
      with:
          bundle: ShijimaQt.flatpak
          manifest-path: com.pixelomer.ShijimaQt.yaml
          cache-key: flatpak-builder-${{ github.sha }}
